# Generated by Django 3.1.7 on 2021-03-21 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeuser',
            name='display_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
